<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJfdsBF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJfdsBF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSJfdsBF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSJfdsBF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSJfdsBF\App_KernelDevDebugContainer([
    'container.build_hash' => 'SJfdsBF',
    'container.build_id' => 'a363e0eb',
    'container.build_time' => 1722521966,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJfdsBF');
